=== Steigerwald/imperial-assault-data/schemas/agenda-cards.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "agenda-cards.json#",
  "title": "Schema for the agenda cards data file",
  "type": "object",
  "definitions": {},
  "properties": {
    "id": {
      "type": "integer",
      "description": "Id for entry",
      "minimum": 0
    },
    "name": {
      "type": "string",
      "description": "Agenda card name",
      "minLength": 1
    },
    "influence": {
      "description": "The influence cost associated obtaining this agenda card.",
      "type": "integer",
      "minimum": 1,
      "maximum": 4
    },
    "agenda_id": {
      "description": "Foreign key id for entry in data/agenda-decks.json",
      "type": "integer",
      "minimum": 0
    },
    "mission": {
      "description": "Determines if the agenda card is a mission or not",
      "type": "boolean"
    },
    "image": {
      "description": "The file path for this command card's image.",
      "$ref": "definitions.json#/definitions/image-file-path"
    }
  },
  "required": [
    "id",
    "name",
    "influence",
    "agenda_id",
    "mission",
    "image"
  ],
  "additionalProperties": false
}

=== Steigerwald/imperial-assault-data/data/agenda-cards.json
[
  {
    "id": 0,
    "name": "Imperial Informants",
    "agenda_id": 0,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/agents-of-the-empire-imperial-informants.png"
  },
  {
    "id": 1,
    "name": "Impounded",
    "agenda_id": 0,
    "influence": 4,
    "mission": true,
    "image": "agenda-cards/agents-of-the-empire-impounded.png"
  },
  {
    "id": 2,
    "name": "Tracking Beacon",
    "agenda_id": 0,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/agents-of-the-empire-tracking-beacon.png"
  },
  {
    "id": 3,
    "name": "High-Value Target",
    "agenda_id": 1,
    "influence": 2,
    "mission": false,
    "image": "agenda-cards/for-the-right-price-high-value-target.png"
  },
  {
    "id": 4,
    "name": "Hired Help",
    "agenda_id": 1,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/for-the-right-price-hired-help.png"
  },
  {
    "id": 5,
    "name": "Wanted",
    "agenda_id": 1,
    "influence": 4,
    "mission": true,
    "image": "agenda-cards/for-the-right-price-wanted.png"
  },
  {
    "id": 6,
    "name": "Fire at Will",
    "agenda_id": 2,
    "influence": 2,
    "mission": false,
    "image": "agenda-cards/imperial-discipline-fire-at-will.png"
  },
  {
    "id": 7,
    "name": "Impending Doom",
    "agenda_id": 2,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/imperial-discipline-impending-doom.png"
  },
  {
    "id": 8,
    "name": "Tactical Maneuvering",
    "agenda_id": 2,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/imperial-discipline-tactical-maneuvering.png"
  },
  {
    "id": 9,
    "name": "Interrogation Protocol",
    "agenda_id": 3,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/imperial-industry-interrogation-protocol.png"
  },
  {
    "id": 10,
    "name": "Means of Production",
    "agenda_id": 3,
    "influence": 3,
    "mission": true,
    "image": "agenda-cards/imperial-industry-means-of-production.png"
  },
  {
    "id": 11,
    "name": "Restorative Supplies",
    "agenda_id": 3,
    "influence": 2,
    "mission": false,
    "image": "agenda-cards/imperial-industry-restorative-supplies.png"
  },
  {
    "id": 12,
    "name": "ISB Enforcers",
    "agenda_id": 4,
    "influence": 2,
    "mission": false,
    "image": "agenda-cards/imperial-security-bureau-isb-enforcers.png"
  },
  {
    "id": 13,
    "name": "Imperial Operative",
    "agenda_id": 4,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/imperial-security-bureau-imperial-operative.png"
  },
  {
    "id": 14,
    "name": "Internal Affairs",
    "agenda_id": 4,
    "influence": 2,
    "mission": false,
    "image": "agenda-cards/imperial-security-bureau-internal-affairs.png"
  },
  {
    "id": 15,
    "name": "A Dark Power",
    "agenda_id": 5,
    "influence": 2,
    "mission": false,
    "image": "agenda-cards/lord-vaders-command-a-dark-power.png"
  },
  {
    "id": 16,
    "name": "As You Wish",
    "agenda_id": 5,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/lord-vaders-command-as-you-wish.png"
  },
  {
    "id": 17,
    "name": "Dark Obsession",
    "agenda_id": 5,
    "influence": 3,
    "mission": true,
    "image": "agenda-cards/lord-vaders-command-dark-obsession.png"
  },
  {
    "id": 18,
    "name": "Breaking Point",
    "agenda_id": 6,
    "influence": 3,
    "mission": true,
    "image": "agenda-cards/retaliation-breaking-point.png"
  },
  {
    "id": 19,
    "name": "Tactical Explosives",
    "agenda_id": 6,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/retaliation-tactical-explosives.png"
  },
  {
    "id": 20,
    "name": "Weakness Revealed",
    "agenda_id": 6,
    "influence": 2,
    "mission": false,
    "image": "agenda-cards/retaliation-weakness-revealed.png"
  },
  {
    "id": 21,
    "name": "Death Mark",
    "agenda_id": 7,
    "influence": 2,
    "mission": false,
    "image": "agenda-cards/pursuit-of-the-enemy-death-mark.png"
  },
  {
    "id": 22,
    "name": "Fire in the Sky",
    "agenda_id": 7,
    "influence": 3,
    "mission": true,
    "image": "agenda-cards/pursuit-of-the-enemy-fire-in-the-sky.png"
  },
  {
    "id": 23,
    "name": "Strike and Subdue",
    "agenda_id": 7,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/pursuit-of-the-enemy-strike-and-subdue.png"
  },
  {
    "id": 24,
    "name": "Advanced Prototypes",
    "agenda_id": 8,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/the-empires-reach-advanced-prototypes.png"
  },
  {
    "id": 25,
    "name": "Data Security",
    "agenda_id": 8,
    "influence": 2,
    "mission": false,
    "image": "agenda-cards/the-empires-reach-data-security.png"
  },
  {
    "id": 26,
    "name": "Infiltrated",
    "agenda_id": 8,
    "influence": 3,
    "mission": true,
    "image": "agenda-cards/the-empires-reach-infiltrated.png"
  },
  {
    "id": 27,
    "name": "Counter Strike",
    "agenda_id": 9,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/defensive-tactics-counter-strike.png"
  },
  {
    "id": 28,
    "name": "Enhanced Armor",
    "agenda_id": 9,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/defensive-tactics-enhanced-armor.png"
  },
  {
    "id": 29,
    "name": "Personal Shield Generators",
    "agenda_id": 9,
    "influence": 2,
    "mission": false,
    "image": "agenda-cards/defensive-tactics-personal-shield-generators.png"
  },
  {
    "id": 30,
    "name": "Bestial Fury",
    "agenda_id": 10,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/natural-warfare-bestial-fury.png"
  },
  {
    "id": 31,
    "name": "Exposed to the Elements",
    "agenda_id": 10,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/natural-warfare-exposed-to-the-elements.png"
  },
  {
    "id": 32,
    "name": "Unchained",
    "agenda_id": 10,
    "influence": 2,
    "mission": false,
    "image": "agenda-cards/natural-warfare-unchained.png"
  },
  {
    "id": 33,
    "name": "Blackmail",
    "agenda_id": 11,
    "influence": 2,
    "mission": false,
    "image": "agenda-cards/enhanced-interrogation-blackmail.png"
  },
  {
    "id": 34,
    "name": "Learn Their Weaknesses",
    "agenda_id": 11,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/enhanced-interrogation-learn-their-weaknesses.png"
  },
  {
    "id": 35,
    "name": "Weak Links",
    "agenda_id": 11,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/enhanced-interrogation-weak-links.png"
  },
  {
    "id": 36,
    "name": "Contingency Plan",
    "agenda_id": 12,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/evasive-maneuvers-contingency-plan.png"
  },
  {
    "id": 37,
    "name": "Feigned Retreat",
    "agenda_id": 12,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/evasive-maneuvers-feigned-retreat.png"
  },
  {
    "id": 38,
    "name": "Hasty Ambush",
    "agenda_id": 12,
    "influence": 2,
    "mission": false,
    "image": "agenda-cards/evasive-maneuvers-hasty-ambush.png"
  },
  {
    "id": 39,
    "name": "Abandoned Contract",
    "agenda_id": 13,
    "influence": 2,
    "mission": false,
    "image": "agenda-cards/guild-hunters-abandoned-contract.png"
  },
  {
    "id": 40,
    "name": "Call Your Shot",
    "agenda_id": 13,
    "influence": 2,
    "mission": false,
    "image": "agenda-cards/guild-hunters-call-your-shot.png"
  },
  {
    "id": 41,
    "name": "Shoot First",
    "agenda_id": 13,
    "influence": 2,
    "mission": false,
    "image": "agenda-cards/guild-hunters-shoot-first.png"
  },
  {
    "id": 42,
    "name": "Jetpacks",
    "agenda_id": 14,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/persistence-jetpacks.png"
  },
  {
    "id": 43,
    "name": "No Rest for the Weary",
    "agenda_id": 14,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/persistence-no-rest-for-the-weary.png"
  },
  {
    "id": 44,
    "name": "Snap Fire",
    "agenda_id": 14,
    "influence": 2,
    "mission": false,
    "image": "agenda-cards/persistence-snap-fire.png"
  },
  {
    "id": 45,
    "name": "Binary Revolution",
    "agenda_id": 15,
    "influence": 3,
    "mission": true,
    "image": "agenda-cards/droid-uprising-binary-revolution.png"
  },
  {
    "id": 46,
    "name": "Firepower Upgrade",
    "agenda_id": 15,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/droid-uprising-firepower-upgrade.png"
  },
  {
    "id": 47,
    "name": "Sabotaged Plans",
    "agenda_id": 15,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/droid-uprising-sabotaged-plans.png"
  },
  {
    "id": 48,
    "name": "Best of the Best",
    "agenda_id": 16,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/crimson-empire-best-of-the-best.png"
  },
  {
    "id": 49,
    "name": "Infection",
    "agenda_id": 16,
    "influence": 3,
    "mission": true,
    "image": "agenda-cards/crimson-empire-infection.png"
  },
  {
    "id": 50,
    "name": "Pulling the Strings",
    "agenda_id": 16,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/crimson-empire-pulling-the-strings.png"
  },
  {
    "id": 51,
    "name": "By Any Means Necessary",
    "agenda_id": 17,
    "influence": 1,
    "mission": false,
    "image": "agenda-cards/soldiers-for-hire-by-any-means-necessary.png"
  },
  {
    "id": 52,
    "name": "No Disintegrations",
    "agenda_id": 17,
    "influence": 2,
    "mission": false,
    "image": "agenda-cards/soldiers-for-hire-no-disintegrations.png"
  },
  {
    "id": 53,
    "name": "Predator and Prey",
    "agenda_id": 17,
    "influence": 3,
    "mission": true,
    "image": "agenda-cards/soldiers-for-hire-predator-and-prey.png"
  },
  {
    "id": 54,
    "name": "Military Presence",
    "agenda_id": 18,
    "influence": 1,
    "mission": false,
