=== Steigerwald/imperial-assault-data/schemas/deployment-cards.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "deployment-cards.json#",
  "title": "Schema for the deployment cards data file",
  "type": "object",
  "definitions": {},
  "properties": {
    "id": {
      "type": "integer",
      "description": "Id for entry",
      "minimum": 0
    },
    "name": {
      "type": "string",
      "description": "Deployment card name",
      "minLength": 1
    },
    "iaspec": {
      "type": "string",
      "description": "iaspec code",
      "minLength": 1
    },
    "description": {
      "description": "Deployment card description",
      "oneOf": [
        {
          "type": "string",
          "minLength": 1
        },
        {
          "type": "null"
        }
      ]
    },
    "elite": {
      "description": "Determines if the deployment card is elite or not",
      "type": "boolean"
    },
    "unique": {
      "description": "Determines if the deployment card is unique or not",
      "type": "boolean"
    },
    "affiliation": {
      "description": "Affiliation for this deployment card.",
      "$ref": "definitions.json#/definitions/affiliation"
    },
    "modes": {
      "type": "array",
      "minItems": 0,
      "description": "Game modes in which this deployment card can be used.",
      "uniqueItems": true,
      "items": {
          "type": "string",
          "description": "A game mode in which this deployment card can be used.",
          "enum": [
            "Campaign",
            "Skirmish"
          ]
      }

    },
    "image": {
      "description": "The file path for this deployment card's image.",
      "$ref": "definitions.json#/definitions/image-file-path"
    },
    "traits": {
      "type": "array",
      "minItems": 1,
      "description": "Traits that apply to this deployment card.",
      "uniqueItems": true,
      "items": {
        "description": "A trait that applies to this deployment card.",
        "$ref": "definitions.json#/definitions/deployment-trait"
      }
    },
    "deployment_cost": {
      "description": "The cost associated with deploying this deployment card.",
      "type": "integer"
    },
    "reinforce_cost": {
      "description": "The cost associated with re-deploying a unit associated with this deployment card's (if appropriate).",
      "oneOf":[
        {
          "type": "integer",
          "minimum": 1
        },
        {
          "type": "null"
        }
      ]
    },
    "health": {
      "description": "This deployment's health (if appropriate).",
      "oneOf":[
        {
          "type": "integer",
          "minimum": 1
        },
        {
          "type": "null"
        }
      ]
    },
    "speed": {
      "description": "This deployment's speed (if appropriate).",
      "oneOf":[
        {
          "type": "integer",
          "minimum": 1
        },
        {
          "type": "null"
        }
      ]
    },
    "deployment_group": {
      "description": "The number of units that get added to the board when deploying this deployment card.",
      "oneOf":[
        {
          "type": "integer",
          "minimum": 1
        },
        {
          "type": "null"
        }
      ]
    }
  },
  "required": [
    "id",
    "iaspec",
    "name",
    "image",
    "traits",
    "description",
    "elite",
    "unique",
    "deployment_group",
    "reinforce_cost",
    "deployment_cost",
    "affiliation",
    "modes",
    "health",
    "speed"
  ],
  "additionalProperties": false
}

=== Steigerwald/imperial-assault-data/data/deployment-cards.json
[
  {
    "id": 0,
    "name": "0-0-0",
    "description": "Specialized in Pain",
    "elite": true,
    "unique": true,
    "affiliation": "Imperial",
    "traits": [
      "Droid"
    ],
    "modes": [
      "Campaign",
      "Skirmish"
    ],
    "deployment_cost": 4,
    "reinforce_cost": null,
    "deployment_group": 1,
    "image": "deployment-cards/0-0-0-specialized-in-pain.png",
    "iaspec": "000",
    "health": 8,
    "speed": 4
  },
  {
    "id": 1,
    "name": "AT-ST",
    "description": null,
    "elite": true,
    "unique": false,
    "affiliation": "Imperial",
    "traits": [
      "Heavy Weapon",
      "Vehicle"
    ],
    "modes": [
      "Campaign",
      "Skirmish"
    ],
    "deployment_cost": 14,
    "reinforce_cost": null,
    "deployment_group": 1,
    "image": "deployment-cards/at-st-elite.png",
    "iaspec": "eliteatst",
    "health": 15,
    "speed": 4
  },
  {
    "id": 2,
    "name": "Advanced Com Systems",
    "description": null,
    "elite": false,
    "unique": true,
    "affiliation": "Imperial",
    "traits": [
      "Skirmish Upgrade"
    ],
    "modes": [
      "Skirmish"
    ],
    "deployment_cost": 1,
    "reinforce_cost": null,
    "deployment_group": null,
    "image": "deployment-cards/advanced-com-systems-skirmish.png",
    "iaspec": "advancedcomsystems",
    "health": null,
    "speed": null
  },
  {
    "id": 3,
    "name": "Agent Blaise",
    "description": "ISB Interrogator",
    "elite": true,
    "unique": true,
    "affiliation": "Imperial",
    "traits": [
      "Leader",
      "Spy"
    ],
    "modes": [
      "Campaign"
    ],
    "deployment_cost": 6,
    "reinforce_cost": null,
    "deployment_group": 1,
    "image": "deployment-cards/agent-blaise-isb-interrogator-campaign.png",
    "iaspec": "agentblaisecampaign",
    "health": 8,
    "speed": 4
  },
  {
    "id": 4,
    "name": "Agent Blaise",
    "description": "ISB Interrogator",
    "elite": true,
    "unique": true,
    "affiliation": "Imperial",
    "traits": [
      "Leader",
      "Spy"
    ],
    "modes": [
      "Skirmish"
    ],
    "deployment_cost": 6,
    "reinforce_cost": null,
    "deployment_group": 1,
    "image": "deployment-cards/agent-blaise-isb-interrogator-skirmish.png",
    "iaspec": "agentblaiseskirmish",
    "health": 8,
    "speed": 4
  },
  {
    "id": 5,
    "name": "Alliance Ranger",
    "description": null,
    "elite": false,
    "unique": false,
    "affiliation": "Rebel",
    "traits": [
      "Hunter",
      "Trooper"
    ],
    "modes": [
      "Campaign",
      "Skirmish"
    ],
    "deployment_cost": 9,
    "reinforce_cost": 3,
    "deployment_group": 3,
    "image": "deployment-cards/alliance-ranger.png",
    "iaspec": "allianceranger",
    "health": 5,
    "speed": 4
  },
  {
    "id": 6,
    "name": "Alliance Ranger",
    "description": null,
    "elite": true,
    "unique": false,
    "affiliation": "Rebel",
    "traits": [
      "Hunter",
      "Trooper"
    ],
    "modes": [
      "Campaign",
      "Skirmish"
    ],
    "deployment_cost": 12,
    "reinforce_cost": 4,
    "deployment_group": 3,
    "image": "deployment-cards/alliance-ranger-elite.png",
    "iaspec": "eliteallianceranger",
    "health": 7,
    "speed": 4
  },
  {
    "id": 7,
    "name": "Alliance Smuggler",
    "description": null,
    "elite": false,
    "unique": false,
    "affiliation": "Rebel",
    "traits": [
      "Smuggler"
    ],
    "modes": [
      "Campaign",
      "Skirmish"
    ],
    "deployment_cost": 2,
    "reinforce_cost": null,
    "deployment_group": 1,
    "image": "deployment-cards/alliance-smuggler.png",
    "iaspec": "alliancesmuggler",
    "health": 3,
    "speed": 4
  },
  {
    "id": 8,
    "name": "Alliance Smuggler",
    "description": null,
    "elite": true,
    "unique": false,
    "affiliation": "Rebel",
    "traits": [
      "Smuggler"
    ],
    "modes": [
      "Campaign",
      "Skirmish"
    ],
    "deployment_cost": 4,
    "reinforce_cost": null,
    "deployment_group": 1,
    "image": "deployment-cards/alliance-smuggler-elite.png",
    "iaspec": "elitealliancesmuggler",
    "health": 5,
    "speed": 5
  },
  {
    "id": 9,
    "name": "BT-1",
    "description": "Destructive Assassin",
    "elite": true,
    "unique": true,
    "affiliation": "Imperial",
    "traits": [
      "Droid",
      "Heavy Weapon",
      "Hunter"
    ],
    "modes": [
      "Campaign",
      "Skirmish"
    ],
    "deployment_cost": 6,
    "reinforce_cost": null,
    "deployment_group": 1,
    "image": "deployment-cards/bt-1-destructive-assassin.png",
    "iaspec": "bt1",
    "health": 10,
    "speed": 4
  },
  {
    "id": 10,
    "name": "Balance of the Force",
    "description": null,
    "elite": false,
    "unique": true,
    "affiliation": "Rebel",
    "traits": [
      "Skirmish Upgrade"
    ],
    "modes": [
      "Skirmish"
    ],
    "deployment_cost": 1,
    "reinforce_cost": null,
    "deployment_group": null,
    "image": "deployment-cards/balance-of-the-force-skirmish.png",
    "iaspec": "balanceoftheforce",
    "health": null,
    "speed": null
  },
  {
    "id": 11,
    "name": "Bantha Rider",
    "description": null,
    "elite": true,
    "unique": false,
    "affiliation": "Mercenary",
    "traits": [
      "Brawler",
      "Creature"
    ],
    "modes": [
      "Campaign",
      "Skirmish"
    ],
    "deployment_cost": 9,
    "reinforce_cost": null,
    "deployment_group": 1,
    "image": "deployment-cards/bantha-rider-elite.png",
    "iaspec": "elitebantharider",
    "health": 21,
    "speed": 5
  },
  {
    "id": 12,
    "name": "Beast Tamer",
    "description": null,
    "elite": false,
    "unique": true,
    "affiliation": "Mercenary",
    "traits": [
      "Skirmish Upgrade"
    ],
    "modes": [
      "Skirmish"
    ],
    "deployment_cost": 1,
    "reinforce_cost": null,
    "deployment_group": null,
    "image": "deployment-cards/beast-tamer-skirmish.png",
    "iaspec": "beasttamer",
    "health": null,
    "speed": null
  },
  {
    "id": 13,
    "name": "Biv Bodhrik",
    "description": null,
    "elite": false,
    "unique": true,
    "affiliation": "Rebel",
    "traits": [
      "Brawler",
      "Hunter"
    ],
    "modes": [
      "Skirmish"
    ],
    "deployment_cost": 9,
    "reinforce_cost": null,
    "deployment_group": 1,
    "image": "deployment-cards/biv-bodhrik-skirmish.png",
    "iaspec": "bivbodhrik",
    "health": 8,
    "speed": 4
  },
  {
    "id": 14,
    "name": "Black Market",
    "description": null,
    "elite": false,
    "unique": true,
    "affiliation": "Mercenary",
    "traits": [
      "Skirmish Upgrade"
    ],
    "modes": [
      "Skirmish"
    ],
    "deployment_cost": 1,
    "reinforce_cost": null,
    "deployment_group": null,
    "image": "deployment-cards/black-market-skirmish.png",
    "iaspec": "blackmarket",
    "health": null,
    "speed": null
  },
  {
    "id": 15,
    "name": "Boba Fett",
    "description": "Infamous Bounty Hunter",
    "elite": true,
    "unique": true,
    "affiliation": "Mercenary",
    "traits": [
      "Hunter"
    ],
    "modes": [
      "Campaign",
      "Skirmish"
    ],
    "deployment_cost": 13,
    "reinforce_cost": null,
    "deployment_group": 1,
    "image": "deployment-cards/boba-fett-infamous-bounty-hunter.png",
    "iaspec": "bobafett",
    "health": 12,
    "speed": 6
  },
  {
    "id": 16,
    "name": "Bossk",
    "description": "Born Hunter",
    "elite": true,
    "unique": true,
    "affiliation": "Mercenary",
    "traits": [
      "Brawler",
      "Hunter"
    ],
    "modes": [
      "Campaign",
      "Skirmish"
    ],
    "deployment_cost": 8,
    "reinforce_cost": null,
    "deployment_group": 1,
    "image": "deployment-cards/bossk-born-hunter.png",
    "iaspec": "bosskmercenary",
    "health": 10,
    "speed": 4
  },
  {
    "id": 17,
    "name": "Bossk",
    "description": "Born Hunter",
    "elite": true,
    "unique": true,
    "affiliation": "Rebel",
    "traits": [
      "Brawler",
      "Hunter"
    ],
    "modes": [
      "Campaign",
      "Skirmish"
    ],
    "deployment_cost": 8,
    "reinforce_cost": null,
    "deployment_group": 1,
    "image": "deployment-cards/bossk-born-hunter.png",
    "iaspec": "bosskrebel",
    "health": 10,
    "speed": 4
  },
  {
    "id": 18,
    "name": "C-3PO",
    "description": "Human-Cyborg Relations",
    "elite": true,
    "unique": true,
    "affiliation": "Rebel",
    "traits": [
      "Droid"
    ],
    "modes": [
      "Campaign",
      "Skirmish"
    ],
    "deployment_cost": 2,
    "reinforce_cost": null,
    "deployment_group": 1,
    "image": "deployment-cards/c-3po-human-cyborg-relations.png",
    "iaspec": "c3po",
    "health": 4,
    "speed": 3
  },
  {
    "id": 19,
    "name": "C1-10P",
    "description": "\"Chopper\"",
    "elite": true,
    "unique": true,
    "affiliation": "Rebel",
    "traits": [
      "Droid"
    ],
    "modes": [
      "Campaign",
      "Skirmish"
    ],
    "deployment_cost": 3,
    "reinforce_cost": null,
    "deployment_group": 1,
    "image": "deployment-cards/c1-10p-chopper.png",
    "iaspec": "c110p",
    "health": 5,
    "speed": 4
  },
  {
    "id": 20,
    "name": "Captain Terro",
    "description": "Wasteland Enforcer",
    "elite": true,
    "unique": true,
    "affiliation": "Imperial",
    "traits": [
      "Creature",
      "Leader",
      "Trooper"
    ],
    "modes": [
      "Campaign",
      "Skirmish"
    ],
    "deployment_cost": 7,
    "reinforce_cost": null,
    "deployment_group": 1,
    "image": "deployment-cards/captain-terro-wasteland-enforcer.png",
    "iaspec": "captainterro",
    "health": 13,
    "speed": 5
  },
  {
    "id": 21,
    "name": "Channel the Force",
    "description": null,
    "elite": false,
    "unique": true,
    "affiliation": "Neutral",
    "traits": [
      "Skirmish Upgrade"
    ],
    "modes": [
      "Skirmish"
    ],
    "deployment_cost": 1,
    "reinforce_cost": null,
    "deployment_group": null,
