=== Steigerwald/imperial-assault-data/schemas/hero-class-cards.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "hero-class-cards.json#",
  "title": "Schema for the hero class cards data file",
  "type": "object",
  "definitions": {},
  "properties": {
    "id": {
      "type": "integer",
      "description": "Id for entry",
      "minimum": 0
    },
    "hero_id": {
      "type": "integer",
      "description": "Foreign key id for entry in data/heroes.json",
      "minimum": 0
    },
    "name": {
      "type": "string",
      "description": "Hero class card name",
      "minLength": 1
    },
    "image": {
      "description": "The file path for this hero class card's image.",
      "$ref": "definitions.json#/definitions/image-file-path"
    },
    "xp": {
      "description": "Hero class xp cost",
      "oneOf":[
        {
          "type": "integer",
          "minimum": 1,
          "maximum": 4
        },
        {
          "type": "null"
        }
      ]
    },
    "type": {
      "description": "Hero class card type",
      "$ref": "definitions.json#/definitions/buff-type"
    },
    "traits": {
      "description": "Traits that apply to this hero class card.",
      "oneOf": [
        {
          "type": "array",
          "minItems": 1,
          "uniqueItems": true,
          "items": {
            "description": "A trait that applies to this hero class card.",
            "$ref": "definitions.json#/definitions/item-trait"
          }
        },
        {
          "type": "null"
        }
      ]
    }
  },
  "required": [
    "id",
    "name",
    "image",
    "hero_id",
    "xp",
    "type",
    "traits"
  ],
  "additionalProperties": false
}

=== Steigerwald/imperial-assault-data/data/hero-class-cards.json
[
  {
    "id": 0,
    "name": "Plasteel Staff",
    "hero_id": 0,
    "xp": null,
    "image": "hero-class-cards/diala-passil-plasteel-staff.png",
    "type": "Melee Weapon",
    "traits": [
      "Staff"
    ]
  },
  {
    "id": 1,
    "name": "Force Throw",
    "hero_id": 0,
    "xp": 1,
    "image": "hero-class-cards/diala-passil-force-throw.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 2,
    "name": "Infantry Rifle",
    "hero_id": 1,
    "xp": null,
    "image": "hero-class-cards/fenn-signis-infantry-rifle.png",
    "type": "Ranged Weapon",
    "traits": [
      "Blaster",
      "Rifle"
    ]
  },
  {
    "id": 3,
    "name": "Force Adept",
    "hero_id": 0,
    "xp": 1,
    "image": "hero-class-cards/diala-passil-force-adept.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 4,
    "name": "Tactical Movement",
    "hero_id": 1,
    "xp": 1,
    "image": "hero-class-cards/fenn-signis-tactical-movement.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 5,
    "name": "Battle Meditation",
    "hero_id": 0,
    "xp": 2,
    "image": "hero-class-cards/diala-passil-battle-meditation.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 6,
    "name": "Take Cover",
    "hero_id": 1,
    "xp": 1,
    "image": "hero-class-cards/fenn-signis-take-cover.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 7,
    "name": "Defensive Stance",
    "hero_id": 0,
    "xp": 2,
    "image": "hero-class-cards/diala-passil-defensive-stance.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 8,
    "name": "Adrenaline Rush",
    "hero_id": 1,
    "xp": 2,
    "image": "hero-class-cards/fenn-signis-adrenaline-rush.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 9,
    "name": "Art of Movement",
    "hero_id": 0,
    "xp": 3,
    "image": "hero-class-cards/diala-passil-art-of-movement.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 10,
    "name": "Weapon Expert",
    "hero_id": 1,
    "xp": 2,
    "image": "hero-class-cards/fenn-signis-weapon-expert.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 11,
    "name": "Snap Kick",
    "hero_id": 0,
    "xp": 3,
    "image": "hero-class-cards/diala-passil-snap-kick.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 12,
    "name": "Suppressive Fire",
    "hero_id": 1,
    "xp": 3,
    "image": "hero-class-cards/fenn-signis-suppressive-fire.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 13,
    "name": "Way of the Sarlacc",
    "hero_id": 0,
    "xp": 4,
    "image": "hero-class-cards/diala-passil-way-of-the-sarlacc.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 14,
    "name": "Trench Fighter",
    "hero_id": 1,
    "xp": 3,
    "image": "hero-class-cards/fenn-signis-trench-fighter.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 15,
    "name": "Dancing Weapon",
    "hero_id": 0,
    "xp": 4,
    "image": "hero-class-cards/diala-passil-dancing-weapon.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 16,
    "name": "Rebel Elite",
    "hero_id": 1,
    "xp": 4,
    "image": "hero-class-cards/fenn-signis-rebel-elite.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 17,
    "name": "Vibro-Ax",
    "hero_id": 2,
    "xp": null,
    "image": "hero-class-cards/gaarkhan-vibro-ax.png",
    "type": "Melee Weapon",
    "traits": [
      "Blade"
    ]
  },
  {
    "id": 18,
    "name": "Superior Positioning",
    "hero_id": 1,
    "xp": 4,
    "image": "hero-class-cards/fenn-signis-superior-positioning.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 19,
    "name": "Wookiee Fortitude",
    "hero_id": 2,
    "xp": 1,
    "image": "hero-class-cards/gaarkhan-wookiee-fortitude.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 20,
    "name": "Wookie Loyalty",
    "hero_id": 2,
    "xp": 1,
    "image": "hero-class-cards/gaarkhan-wookie-loyalty.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 21,
    "name": "Ferocity",
    "hero_id": 2,
    "xp": 2,
    "image": "hero-class-cards/gaarkhan-ferocity.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 22,
    "name": "Staggering Blow",
    "hero_id": 2,
    "xp": 2,
    "image": "hero-class-cards/gaarkhan-staggering-blow.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 23,
    "name": "Rampage",
    "hero_id": 2,
    "xp": 3,
    "image": "hero-class-cards/gaarkhan-rampage.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 24,
    "name": "Vicious Strike",
    "hero_id": 2,
    "xp": 3,
    "image": "hero-class-cards/gaarkhan-vicious-strike.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 25,
    "name": "Brutal Cleave",
    "hero_id": 2,
    "xp": 4,
    "image": "hero-class-cards/gaarkhan-brutal-cleave.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 26,
    "name": "Unstoppable",
    "hero_id": 2,
    "xp": 4,
    "image": "hero-class-cards/gaarkhan-unstoppable.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 27,
    "name": "Holdout Blaster",
    "hero_id": 3,
    "xp": null,
    "image": "hero-class-cards/gideon-argus-holdout-blaster.png",
    "type": "Ranged Weapon",
    "traits": [
      "Blaster",
      "Pistol"
    ]
  },
  {
    "id": 28,
    "name": "Called Shot",
    "hero_id": 3,
    "xp": 1,
    "image": "hero-class-cards/gideon-argus-called-shot.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 29,
    "name": "Military Efficiency",
    "hero_id": 3,
    "xp": 1,
    "image": "hero-class-cards/gideon-argus-military-efficiency.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 30,
    "name": "Air of Command",
    "hero_id": 3,
    "xp": 2,
    "image": "hero-class-cards/gideon-argus-air-of-command.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 31,
    "name": "Mobile Tactician",
    "hero_id": 3,
    "xp": 2,
    "image": "hero-class-cards/gideon-argus-mobile-tactician.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 32,
    "name": "For the Cause",
    "hero_id": 3,
    "xp": 3,
    "image": "hero-class-cards/gideon-argus-for-the-cause.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 33,
    "name": "Rallying Shout",
    "hero_id": 3,
    "xp": 3,
    "image": "hero-class-cards/gideon-argus-rallying-shout.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 34,
    "name": "Hammer and Anvil",
    "hero_id": 3,
    "xp": 4,
    "image": "hero-class-cards/gideon-argus-hammer-and-anvil.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 35,
    "name": "Masterstroke",
    "hero_id": 3,
    "xp": 4,
    "image": "hero-class-cards/gideon-argus-masterstroke.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 36,
    "name": "Repeating Blaster",
    "hero_id": 4,
    "xp": null,
    "image": "hero-class-cards/biv-bodhrik-repeating-blaster.png",
    "type": "Ranged Weapon",
    "traits": [
      "Blaster",
      "Heavy"
    ]
  },
  {
    "id": 37,
    "name": "Advance",
    "hero_id": 4,
    "xp": 1,
    "image": "hero-class-cards/biv-bodhrik-advance.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 38,
    "name": "Shake It Off",
    "hero_id": 4,
    "xp": 1,
    "image": "hero-class-cards/biv-bodhrik-shake-it-off.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 39,
    "name": "Crushing Blow",
    "hero_id": 4,
    "xp": 2,
    "image": "hero-class-cards/biv-bodhrik-crushing-blow.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 40,
    "name": "Into The Fray",
    "hero_id": 4,
    "xp": 2,
    "image": "hero-class-cards/biv-bodhrik-into-the-fray.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 41,
    "name": "Trophy Armor",
    "hero_id": 4,
    "xp": 3,
    "image": "hero-class-cards/biv-bodhrik-trophy-armor.png",
    "type": "Armor",
    "traits": [
      "Armor",
      "Heavy"
    ]
  },
  {
    "id": 42,
    "name": "Vibrobayonet",
    "hero_id": 4,
    "xp": 3,
    "image": "hero-class-cards/biv-bodhrik-vibrobayonet.png",
    "type": "Ranged Weapon Modification",
    "traits": [
      "Modification",
      "Blade"
    ]
  },
  {
    "id": 43,
    "name": "Stay Down",
    "hero_id": 4,
    "xp": 4,
    "image": "hero-class-cards/biv-bodhrik-stay-down.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 44,
    "name": "Modified Blaster",
    "hero_id": 5,
    "xp": null,
    "image": "hero-class-cards/saska-teft-modified-blaster.png",
    "type": "Ranged Weapon",
    "traits": [
      "Blaster",
      "Pistol"
    ]
  },
  {
    "id": 45,
    "name": "Final Stand",
    "hero_id": 4,
    "xp": 4,
    "image": "hero-class-cards/biv-bodhrik-final-stand.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 46,
    "name": "Unstable Device",
    "hero_id": 5,
    "xp": 1,
    "image": "hero-class-cards/saska-teft-unstable-device.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 47,
    "name": "Tool Kit",
    "hero_id": 5,
    "xp": 1,
    "image": "hero-class-cards/saska-teft-tool-kit.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 48,
    "name": "Structural Weakness",
    "hero_id": 5,
    "xp": 2,
    "image": "hero-class-cards/saska-teft-structural-weakness.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 49,
    "name": "Energy Shield",
    "hero_id": 5,
    "xp": 2,
    "image": "hero-class-cards/saska-teft-energy-shield.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 50,
    "name": "Gadgeteer",
    "hero_id": 5,
    "xp": 3,
    "image": "hero-class-cards/saska-teft-gadgeteer.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 51,
    "name": "Power Converter",
    "hero_id": 5,
    "xp": 3,
    "image": "hero-class-cards/saska-teft-power-converter.png",
    "type": "Feat",
    "traits": null
  },
  {
    "id": 52,
