=== Steigerwald/imperial-assault-data/schemas/reward-cards.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "reward-cards.json#",
  "title": "Schema for the reward cards data file",
  "type": "object",
  "definitions": {},
  "properties": {
    "id": {
      "type": "integer",
      "description": "Id for entry",
      "minimum": 0
    },
    "name": {
      "type": "string",
      "description": "Reward card name",
      "minLength": 1
    },
    "image": {
      "description": "The file path for this reward card's image.",
      "$ref": "definitions.json#/definitions/image-file-path"
    },
    "traits": {
      "description": "Traits that apply to this reward card.",
      "oneOf": [
        {
          "type": "array",
          "minItems": 1,
          "uniqueItems": true,
          "items": {
            "description": "A trait that applies to this reward.",
            "$ref": "definitions.json#/definitions/item-trait"
          }
        },
        {
          "type": "null"
        }
      ]
    },
    "type": {
      "description": "Reward type",
      "$ref": "definitions.json#/definitions/buff-type"
    }
  },
  "required": [
    "id",
    "name",
    "image",
    "traits",
    "type"
  ],
  "additionalProperties": false
}

=== Steigerwald/imperial-assault-data/data/rewards-cards.json
[
  {
    "id": 0,
    "name": "Bounty",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/bounty.png"
  },
  {
    "id": 1,
    "name": "Counterparts",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/counterparts.png"
  },
  {
    "id": 2,
    "name": "Hunt Them Down",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/hunt-them-down.png"
  },
  {
    "id": 3,
    "name": "Surveillance Operatives",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/surveillance-operatives.png"
  },
  {
    "id": 4,
    "name": "Tech Goggles",
    "type": "Equipment",
    "traits": [
      "Accessory"
    ],
    "image": "rewards-cards/tech-goggles.png"
  },
  {
    "id": 5,
    "name": "Adrenalin Implant",
    "type": "Equipment",
    "traits": [
      "Accessory"
    ],
    "image": "rewards-cards/adrenalin-implant.png"
  },
  {
    "id": 6,
    "name": "Allied Operations",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/allied-operations.png"
  },
  {
    "id": 7,
    "name": "Fearless Leader",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/fearless-leader.png"
  },
  {
    "id": 8,
    "name": "Imperial Industry",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/imperial-industry.png"
  },
  {
    "id": 9,
    "name": "Life Debt",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/life-debt.png"
  },
  {
    "id": 10,
    "name": "Old Wounds",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/old-wounds.png"
  },
  {
    "id": 11,
    "name": "Peacemaker",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/peacemaker.png"
  },
  {
    "id": 12,
    "name": "Rebel Recon",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/rebel-recon.png"
  },
  {
    "id": 13,
    "name": "Shadow Suit",
    "type": "Armor",
    "traits": [
      "Armor",
      "Light"
    ],
    "image": "rewards-cards/shadow-suit.png"
  },
  {
    "id": 14,
    "name": "Shu Yen's Lightsaber",
    "type": "Melee Weapon",
    "traits": [
      "Lightsaber",
      "Blade"
    ],
    "image": "rewards-cards/shu-yens-lightsaber.png"
  },
  {
    "id": 15,
    "name": "Special Operations",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/special-operations.png"
  },
  {
    "id": 16,
    "name": "Supply Deficit",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/supply-deficit.png"
  },
  {
    "id": 17,
    "name": "The Ways of the Force",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/the-ways-of-the-force.png"
  },
  {
    "id": 18,
    "name": "Veteran Prowess",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/veteran-prowess.png"
  },
  {
    "id": 19,
    "name": "Battle Vision",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/battle-vision.png"
  },
  {
    "id": 20,
    "name": "Iron Hand",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/iron-hand.png"
  },
  {
    "id": 21,
    "name": "Systems Upgrade",
    "type": "Equipment",
    "traits": [
      "Enhancement"
    ],
    "image": "rewards-cards/systems-upgrade.png"
  },
  {
    "id": 22,
    "name": "Cam Droid",
    "type": "Equipment",
    "traits": [
      "Accessory"
    ],
    "image": "rewards-cards/cam-droid.png"
  },
  {
    "id": 23,
    "name": "Lobots Favor",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/lobots-favor.png"
  },
  {
    "id": 24,
    "name": "Radiant Holocron",
    "type": "Equipment",
    "traits": [
      "Accessory"
    ],
    "image": "rewards-cards/radiant-holocron.png"
  },
  {
    "id": 25,
    "name": "Relief Effort",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/relief-effort.png"
  },
  {
    "id": 26,
    "name": "Under the Radar",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/under-the-radar.png"
  },
  {
    "id": 27,
    "name": "Bred for War",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/bred-for-war.png"
  },
  {
    "id": 28,
    "name": "Desperado",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/desperado.png"
  },
  {
    "id": 29,
    "name": "Haymaker",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/haymaker.png"
  },
  {
    "id": 30,
    "name": "Mandalorian Heritage",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/mandalorian-heritage.png"
  },
  {
    "id": 31,
    "name": "Mercenary Ties",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/mercenary-ties.png"
  },
  {
    "id": 32,
    "name": "501st Training",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/501st-training.png"
  },
  {
    "id": 33,
    "name": "Tusken Weaponry",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/tusken-weaponry.png"
  },
  {
    "id": 34,
    "name": "Cautious Approach",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/cautious-approach.png"
  },
  {
    "id": 35,
    "name": "Tactical Advance",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/tactical-advance.png"
  },
  {
    "id": 36,
    "name": "Lady Luck",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/lady-luck.png"
  },
  {
    "id": 37,
    "name": "Mechanical Salvage",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/mechanical-salvage.png"
  },
  {
    "id": 38,
    "name": "Intimidation",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/intimidation.png"
  },
  {
    "id": 39,
    "name": "Quickdraw Holster",
    "type": "Equipment",
    "traits": [
      "Accessory"
    ],
    "image": "rewards-cards/quickdraw-holster.png"
  },
  {
    "id": 40,
    "name": "Alliance Efficiency",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/alliance-efficiency.png"
  },
  {
    "id": 41,
    "name": "Bardottan Shard",
    "type": "Equipment",
    "traits": [
      "Accessory"
    ],
    "image": "rewards-cards/bardottan-shard.png"
  },
  {
    "id": 42,
    "name": "Explosives Clearance",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/explosives-clearance.png"
  },
  {
    "id": 43,
    "name": "Inside Source",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/inside-source.png"
  },
  {
    "id": 44,
    "name": "Intercepted Plans",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/intercepted-plans.png"
  },
  {
    "id": 45,
    "name": "Lessons of History",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/lessons-of-history.png"
  },
  {
    "id": 46,
    "name": "Mercenary Aid",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/mercenary-aid.png"
  },
  {
    "id": 47,
    "name": "Populist Support",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/populist-support.png"
  },
  {
    "id": 48,
    "name": "Power of the Shard",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/power-of-the-shard.png"
  },
  {
    "id": 49,
    "name": "Scouted Enemies",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/scouted-enemies.png"
  },
  {
    "id": 50,
    "name": "Tracked Movements",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/tracked-movements.png"
  },
  {
    "id": 51,
    "name": "Vaders Legion",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/vaders-legion.png"
  },
  {
    "id": 52,
    "name": "Wookiee Roar",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/wookiee-roar.png"
  },
  {
    "id": 53,
    "name": "X-8 Upgrade",
    "type": "Feat",
    "traits": null,
    "image": "rewards-cards/x-8-upgrade.png"
  }
]

=== Steigerwald/imperial-assault-data/data/reward-cards.json
[
  {
    "id": 0,
    "name": "Bounty",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/bounty.png"
  },
  {
    "id": 1,
    "name": "Counterparts",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/counterparts.png"
  },
  {
    "id": 2,
    "name": "Hunt Them Down",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/hunt-them-down.png"
  },
  {
    "id": 3,
    "name": "Surveillance Operatives",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/surveillance-operatives.png"
  },
  {
    "id": 4,
    "name": "Tech Goggles",
    "type": "Equipment",
    "traits": [
      "Accessory"
    ],
    "image": "reward-cards/tech-goggles.png"
  },
  {
    "id": 5,
    "name": "Adrenalin Implant",
    "type": "Equipment",
    "traits": [
      "Accessory"
    ],
    "image": "reward-cards/adrenalin-implant.png"
  },
  {
    "id": 6,
    "name": "Allied Operations",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/allied-operations.png"
  },
  {
    "id": 7,
    "name": "Fearless Leader",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/fearless-leader.png"
  },
  {
    "id": 8,
    "name": "Imperial Industry",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/imperial-industry.png"
  },
  {
    "id": 9,
    "name": "Life Debt",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/life-debt.png"
  },
  {
    "id": 10,
    "name": "Old Wounds",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/old-wounds.png"
  },
  {
    "id": 11,
    "name": "Peacemaker",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/peacemaker.png"
  },
  {
    "id": 12,
    "name": "Rebel Recon",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/rebel-recon.png"
  },
  {
    "id": 13,
    "name": "Shadow Suit",
    "type": "Armor",
    "traits": [
      "Armor",
      "Light"
    ],
    "image": "reward-cards/shadow-suit.png"
  },
  {
    "id": 14,
    "name": "Shu Yen's Lightsaber",
    "type": "Melee Weapon",
    "traits": [
      "Lightsaber",
      "Blade"
    ],
    "image": "reward-cards/shu-yens-lightsaber.png"
  },
  {
    "id": 15,
    "name": "Special Operations",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/special-operations.png"
  },
  {
    "id": 16,
    "name": "Supply Deficit",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/supply-deficit.png"
  },
  {
    "id": 17,
    "name": "The Ways of the Force",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/the-ways-of-the-force.png"
  },
  {
    "id": 18,
    "name": "Veteran Prowess",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/veteran-prowess.png"
  },
  {
    "id": 19,
    "name": "Battle Vision",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/battle-vision.png"
  },
  {
    "id": 20,
    "name": "Iron Hand",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/iron-hand.png"
  },
  {
    "id": 21,
    "name": "Systems Upgrade",
    "type": "Equipment",
    "traits": [
      "Enhancement"
    ],
    "image": "reward-cards/systems-upgrade.png"
  },
  {
    "id": 22,
    "name": "Cam Droid",
    "type": "Equipment",
    "traits": [
      "Accessory"
    ],
    "image": "reward-cards/cam-droid.png"
  },
  {
    "id": 23,
    "name": "Lobots Favor",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/lobots-favor.png"
  },
  {
    "id": 24,
    "name": "Radiant Holocron",
    "type": "Equipment",
    "traits": [
      "Accessory"
    ],
    "image": "reward-cards/radiant-holocron.png"
  },
  {
    "id": 25,
    "name": "Relief Effort",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/relief-effort.png"
  },
  {
    "id": 26,
    "name": "Under the Radar",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/under-the-radar.png"
  },
  {
    "id": 27,
    "name": "Bred for War",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/bred-for-war.png"
  },
  {
    "id": 28,
    "name": "Desperado",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/desperado.png"
  },
  {
    "id": 29,
    "name": "Haymaker",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/haymaker.png"
  },
  {
    "id": 30,
    "name": "Mandalorian Heritage",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/mandalorian-heritage.png"
  },
  {
    "id": 31,
    "name": "Mercenary Ties",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/mercenary-ties.png"
  },
  {
    "id": 32,
    "name": "501st Training",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/501st-training.png"
  },
  {
    "id": 33,
    "name": "Tusken Weaponry",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/tusken-weaponry.png"
  },
  {
    "id": 34,
    "name": "Cautious Approach",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/cautious-approach.png"
  },
  {
    "id": 35,
    "name": "Tactical Advance",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/tactical-advance.png"
  },
  {
    "id": 36,
    "name": "Lady Luck",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/lady-luck.png"
  },
  {
    "id": 37,
    "name": "Mechanical Salvage",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/mechanical-salvage.png"
  },
  {
    "id": 38,
    "name": "Intimidation",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/intimidation.png"
  },
  {
    "id": 39,
    "name": "Quickdraw Holster",
    "type": "Equipment",
    "traits": [
      "Accessory"
    ],
    "image": "reward-cards/quickdraw-holster.png"
  },
  {
    "id": 40,
    "name": "Alliance Efficiency",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/alliance-efficiency.png"
  },
  {
    "id": 41,
    "name": "Bardottan Shard",
    "type": "Equipment",
    "traits": [
      "Accessory"
    ],
    "image": "reward-cards/bardottan-shard.png"
  },
  {
    "id": 42,
    "name": "Explosives Clearance",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/explosives-clearance.png"
  },
  {
    "id": 43,
    "name": "Inside Source",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/inside-source.png"
  },
  {
    "id": 44,
    "name": "Intercepted Plans",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/intercepted-plans.png"
  },
  {
    "id": 45,
    "name": "Lessons of History",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/lessons-of-history.png"
  },
  {
    "id": 46,
    "name": "Mercenary Aid",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/mercenary-aid.png"
  },
  {
    "id": 47,
    "name": "Populist Support",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/populist-support.png"
  },
  {
    "id": 48,
    "name": "Power of the Shard",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/power-of-the-shard.png"
  },
  {
    "id": 49,
    "name": "Scouted Enemies",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/scouted-enemies.png"
  },
  {
    "id": 50,
    "name": "Tracked Movements",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/tracked-movements.png"
  },
  {
    "id": 51,
    "name": "Vaders Legion",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/vaders-legion.png"
  },
  {
    "id": 52,
    "name": "Wookiee Roar",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/wookiee-roar.png"
  },
  {
    "id": 53,
    "name": "X-8 Upgrade",
    "type": "Feat",
    "traits": null,
    "image": "reward-cards/x-8-upgrade.png"
  }
]
