=== Steigerwald/imperial-assault-data/schemas/supply-cards.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "supply-cards.json#",
  "title": "Schema for the supply cards data file",
  "type": "object",
  "definitions": {},
  "properties": {
    "id": {
      "type": "integer",
      "description": "Id for entry",
      "minimum": 0
    },
    "name": {
      "type": "string",
      "description": "Supply card name",
      "minLength": 1
    },
    "image": {
      "description": "The file path for this supply card's image.",
      "$ref": "definitions.json#/definitions/image-file-path"
    },
    "traits": {
      "type": "array",
      "description": "Traits that apply to this supply card.",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "description": "A trait that applies to this supply.",
        "$ref": "definitions.json#/definitions/supply-trait"
      }
    }
  },
  "required": [
    "id",
    "name",
    "image",
    "traits"
  ],
  "additionalProperties": false
}

=== Steigerwald/imperial-assault-data/data/supply-cards.json
[
  {
    "id": 0,
    "name": "Adrenal Stim",
    "traits": [
      "Consumable",
      "Medical"
    ],
    "image": "supply-cards/adrenal-stim.png"
  },
  {
    "id": 1,
    "name": "Artificial Stimulants",
    "traits": [
      "Consumable",
      "Medical"
    ],
    "image": "supply-cards/artificial-stimulants.png"
  },
  {
    "id": 2,
    "name": "Bacta Infusion",
    "traits": [
      "Consumable",
      "Medical"
    ],
    "image": "supply-cards/bacta-infusion.png"
  },
  {
    "id": 3,
    "name": "C1 Comlink",
    "traits": [
      "Consumable",
      "Tool"
    ],
    "image": "supply-cards/c1-comlink.png"
  },
  {
    "id": 4,
    "name": "C22 Frag Grenade",
    "traits": [
      "Consumable",
      "Explosive"
    ],
    "image": "supply-cards/c22-frag-grenade.png"
  },
  {
    "id": 5,
    "name": "Chance Cubes",
    "traits": [
      "Valuable"
    ],
    "image": "supply-cards/chance-cubes.png"
  },
  {
    "id": 6,
    "name": "Emergency Medpac",
    "traits": [
      "Consumable",
      "Medical"
    ],
    "image": "supply-cards/emergency-medpac.png"
  },
  {
    "id": 7,
    "name": "Flash Bomb",
    "traits": [
      "Consumable",
      "Explosive"
    ],
    "image": "supply-cards/flash-bomb.png"
  },
  {
    "id": 8,
    "name": "Flash Emitter",
    "traits": [
      "Consumable",
      "Energy"
    ],
    "image": "supply-cards/flash-emitter.png"
  },
  {
    "id": 9,
    "name": "Grappling Hook",
    "traits": [
      "Tool"
    ],
    "image": "supply-cards/grappling-hook.png"
  },
  {
    "id": 10,
    "name": "Macrobinoculars",
    "traits": [
      "Tool"
    ],
    "image": "supply-cards/macrobinoculars.png"
  },
  {
    "id": 11,
    "name": "Painkillers",
    "traits": [
      "Medical"
    ],
    "image": "supply-cards/painkillers.png"
  },
  {
    "id": 12,
    "name": "Pit Droid",
    "traits": [
      "Droid"
    ],
    "image": "supply-cards/pit-droid.png"
  },
  {
    "id": 13,
    "name": "Power Generator",
    "traits": [
      "Consumable",
      "Energy"
    ],
    "image": "supply-cards/power-generator.png"
  },
  {
    "id": 14,
    "name": "Shock Grenade",
    "traits": [
      "Consumable",
      "Explosive"
    ],
    "image": "supply-cards/shock-grenade.png"
  },
  {
    "id": 15,
    "name": "Troop Data",
    "traits": [
      "Intel"
    ],
    "image": "supply-cards/troop-data.png"
  },
  {
    "id": 16,
    "name": "Turbocharger",
    "traits": [
      "Energy"
    ],
    "image": "supply-cards/turbocharger.png"
  },
  {
    "id": 17,
    "name": "Valuable Goods",
    "traits": [
      "Valuable"
    ],
    "image": "supply-cards/valuable-goods.png"
  },
  {
    "id": 18,
    "name": "Weapons Cache",
    "traits": [
      "Tool"
    ],
    "image": "supply-cards/weapons-cache.png"
  },
  {
    "name": "Grappler Arm",
    "id": 19,
    "traits": [
      "Tool"
    ],
    "image": "supply-cards/grappler-arm.png"
  },
  {
    "name": "Shield Pack",
    "id": 20,
    "traits": [
      "Consumable",
      "Tool"
    ],
    "image": "supply-cards/shield-pack.png"
  },
  {
    "name": "Supply Chest",
    "id": 21,
    "traits": [
      "Valuable"
    ],
    "image": "supply-cards/supply-chest.png"
  }
]
