=== Steigerwald/imperial-assault-data/schemas/upgrade-cards.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "upgrade-cards.json#",
  "title": "Schema for the upgrade cards data file",
  "type": "object",
  "definitions": {},
  "properties": {
    "id": {
      "type": "integer",
      "description": "Id for entry",
      "minimum": 0
    },
    "name": {
      "type": "string",
      "description": "Upgrade card name",
      "minLength": 1
    },
    "image": {
      "description": "The file path for this upgrade card's image.",
      "$ref": "definitions.json#/definitions/image-file-path"
    },
    "traits": {
      "type": "array",
      "minItems": 1,
      "description": "Traits that apply to this upgrade card.",
      "uniqueItems": true,
      "items": {
        "description": "A trait that applies to this upgrade.",
        "$ref": "definitions.json#/definitions/item-trait"
      }
    },
    "type": {
      "description": "Upgrade type",
      "$ref": "definitions.json#/definitions/buff-type"
    },
    "tier": {
      "type": "integer",
      "description": "Upgrade Tier",
      "minimum": 1,
      "maximum": 3
    },
    "credits": {
      "type": "integer",
      "description": "Upgrade cost",
      "minimum": 0,
      "multipleOf" : 10
    }
  },
  "required": [
    "id",
    "name",
    "image",
    "traits"
  ],
  "additionalProperties": false
}

=== Steigerwald/imperial-assault-data/data/upgrade-cards.json
[
  {
    "id": 0,
    "tier": 1,
    "name": "Armored Gauntlets",
    "credits": 300,
    "image": "upgrade-cards/armored-gauntlets.png",
    "traits": [
      "Fist"
    ],
    "type": "Melee Weapon"
  },
  {
    "id": 1,
    "tier": 1,
    "name": "Bacta Pump",
    "credits": 300,
    "image": "upgrade-cards/bacta-pump.png",
    "traits": [
      "Accessory"
    ],
    "type": "Equipment"
  },
  {
    "id": 2,
    "tier": 1,
    "name": "Balanced Hilt",
    "credits": 300,
    "image": "upgrade-cards/balanced-hilt.png",
    "traits": [
      "Modification",
      "Balance"
    ],
    "type": "Melee Weapon Modification"
  },
  {
    "id": 3,
    "tier": 1,
    "name": "Combat Coat",
    "credits": 500,
    "image": "upgrade-cards/combat-coat.png",
    "traits": [
      "Armor",
      "Light"
    ],
    "type": "Armor"
  },
  {
    "id": 4,
    "tier": 1,
    "name": "DDC Defender",
    "credits": 550,
    "image": "upgrade-cards/ddc-defender.png",
    "traits": [
      "Blaster",
      "Pistol"
    ],
    "type": "Ranged Weapon"
  },
  {
    "id": 5,
    "tier": 1,
    "name": "DH-17",
    "credits": 200,
    "image": "upgrade-cards/dh-17.png",
    "traits": [
      "Blaster",
      "Pistol"
    ],
    "type": "Ranged Weapon"
  },
  {
    "id": 6,
    "tier": 1,
    "name": "DL-44",
    "credits": 500,
    "image": "upgrade-cards/dl-44.png",
    "traits": [
      "Blaster",
      "Pistol"
    ],
    "type": "Ranged Weapon"
  },
  {
    "id": 7,
    "tier": 1,
    "name": "E-11",
    "credits": 400,
    "image": "upgrade-cards/e-11.png",
    "traits": [
      "Blaster",
      "Rifle"
    ],
    "type": "Ranged Weapon"
  },
  {
    "id": 8,
    "tier": 1,
    "name": "Emergency Injector",
    "credits": 150,
    "image": "upgrade-cards/emergency-injector.png",
    "traits": [
      "Accessory"
    ],
    "type": "Equipment"
  },
  {
    "id": 9,
    "tier": 1,
    "name": "Extended Haft",
    "credits": 300,
    "image": "upgrade-cards/extended-haft.png",
    "traits": [
      "Modification",
      "Balance"
    ],
    "type": "Melee Weapon Modification"
  },
  {
    "id": 10,
    "tier": 1,
    "name": "Gaffi Stick",
    "credits": 200,
    "image": "upgrade-cards/gaffi-stick.png",
    "traits": [
      "Club"
    ],
    "type": "Melee Weapon"
  },
  {
    "id": 11,
    "tier": 1,
    "name": "Hand Cannon",
    "credits": 400,
    "image": "upgrade-cards/hand-cannon.png",
    "traits": [
      "Blaster",
      "Pistol"
    ],
    "type": "Ranged Weapon"
  },
  {
    "id": 12,
    "tier": 1,
    "name": "Marksman Barrel",
    "credits": 300,
    "image": "upgrade-cards/marksman-barrel.png",
    "traits": [
      "Modification",
      "Barrel"
    ],
    "type": "Ranged Weapon Modification"
  },
  {
    "id": 13,
    "tier": 1,
    "name": "Portable Medkit",
    "credits": 450,
    "image": "upgrade-cards/portable-medkit.png",
    "traits": [
      "Accessory"
    ],
    "type": "Equipment"
  },
  {
    "id": 14,
    "tier": 1,
    "name": "Shadowsilk Cloak",
    "credits": 350,
    "image": "upgrade-cards/shadowsilk-cloak.png",
    "traits": [
      "Armor",
      "Light"
    ],
    "type": "Armor"
  },
  {
    "id": 15,
    "tier": 1,
    "name": "Survival Gear",
    "credits": 250,
    "image": "upgrade-cards/survival-gear.png",
    "traits": [
      "Accessory"
    ],
    "type": "Equipment"
  },
  {
    "id": 16,
    "tier": 1,
    "name": "Tactical Display",
    "credits": 300,
    "image": "upgrade-cards/tactical-display.png",
    "traits": [
      "Modification",
      "Sights"
    ],
    "type": "Ranged Weapon Modification"
  },
  {
    "id": 17,
    "tier": 1,
    "name": "Tatooine Hunting Rifle",
    "credits": 250,
    "image": "upgrade-cards/tatooine-hunting-rifle.png",
    "traits": [
      "Projectile",
      "Rifle"
    ],
    "type": "Ranged Weapon"
  },
  {
    "id": 18,
    "tier": 1,
    "name": "Under-Barrel HH-4",
    "credits": 300,
    "image": "upgrade-cards/under-barrel-hh-4.png",
    "traits": [
      "Modification",
      "Barrel"
    ],
    "type": "Ranged Weapon Modification"
  },
  {
    "id": 19,
    "tier": 1,
    "name": "Vibroblade",
    "credits": 300,
    "image": "upgrade-cards/vibroblade.png",
    "traits": [
      "Blade"
    ],
    "type": "Melee Weapon"
  },
  {
    "id": 20,
    "tier": 1,
    "name": "Vibroknife",
    "credits": 150,
    "image": "upgrade-cards/vibroknife.png",
    "traits": [
      "Blade"
    ],
    "type": "Melee Weapon"
  },
  {
    "id": 21,
    "tier": 1,
    "name": "Vibrosword",
    "credits": 350,
    "image": "upgrade-cards/vibrosword.png",
    "traits": [
      "Blade"
    ],
    "type": "Melee Weapon"
  },
  {
    "id": 22,
    "tier": 2,
    "name": "434 \"Deathhammer\"",
    "credits": 600,
    "image": "upgrade-cards/434-deathhammer.png",
    "traits": [
      "Blaster",
      "Pistol"
    ],
    "type": "Ranged Weapon"
  },
  {
    "id": 23,
    "tier": 2,
    "name": "A280",
    "credits": 600,
    "image": "upgrade-cards/a280.png",
    "traits": [
      "Blaster",
      "Rifle"
    ],
    "type": "Ranged Weapon"
  },
  {
    "id": 24,
    "tier": 2,
    "name": "BD-1 Vibro-Ax",
    "credits": 600,
    "image": "upgrade-cards/bd-1-vibro-ax.png",
    "traits": [
      "Blade",
      "Staff"
    ],
    "type": "Melee Weapon"
  },
  {
    "id": 25,
    "tier": 2,
    "name": "Bolt Upgrade",
    "credits": 250,
    "image": "upgrade-cards/bolt-upgrade.png",
    "traits": [
      "Modification",
      "Energy"
    ],
    "type": "Ranged Weapon Modification"
  },
  {
    "id": 26,
    "tier": 2,
    "name": "Combat Coat",
    "credits": 500,
    "image": "upgrade-cards/combat-coat.png",
    "traits": [
      "Armor",
      "Light"
    ],
    "type": "Armor"
  },
  {
    "id": 27,
    "tier": 2,
    "name": "Cybernetic Arm",
    "credits": 350,
    "image": "upgrade-cards/cybernetic-arm.png",
    "traits": [
      "Medical",
      "Enhancement"
    ],
    "type": "Equipment"
  },
  {
    "id": 28,
    "tier": 2,
    "name": "DT-12 Heavy Blaster Pistol",
    "credits": 600,
    "image": "upgrade-cards/dt-12-heavy-blaster-pistol.png",
    "traits": [
      "Blaster",
      "Pistol"
    ],
    "type": "Ranged Weapon"
  },
  {
    "id": 29,
    "tier": 2,
    "name": "Double Vibrosword",
    "credits": 650,
    "image": "upgrade-cards/double-vibrosword.png",
    "traits": [
      "Blade"
    ],
    "type": "Melee Weapon"
  },
  {
    "id": 30,
    "tier": 2,
    "name": "EE-3 Carbine",
    "credits": 550,
    "image": "upgrade-cards/ee-3-carbine.png",
    "traits": [
      "Blaster",
      "Rifle"
    ],
    "type": "Ranged Weapon"
  },
  {
    "id": 31,
    "tier": 2,
    "name": "Energized Hilt",
    "credits": 250,
    "image": "upgrade-cards/energized-hilt.png",
    "traits": [
      "Modification",
      "Energy"
    ],
    "type": "Melee Weapon Modification"
  },
  {
    "id": 32,
    "tier": 2,
    "name": "Environmental Hazard Suit",
    "credits": 600,
    "image": "upgrade-cards/environmental-hazard-suit.png",
    "traits": [
      "Armor"
    ],
    "type": "Armor"
  },
  {
    "id": 33,
    "tier": 2,
    "name": "Extra Ammunition",
    "credits": 300,
    "image": "upgrade-cards/extra-ammunition.png",
    "traits": [
      "Accessory"
    ],
    "type": "Equipment"
  },
  {
    "id": 34,
    "tier": 2,
    "name": "High-Impact Guard",
    "credits": 500,
    "image": "upgrade-cards/high-impact-guard.png",
    "traits": [
      "Modification",
      "Impact"
    ],
    "type": "Melee Weapon Modification"
  },
  {
    "id": 35,
    "tier": 2,
    "name": "Laminate Armor",
    "credits": 700,
    "image": "upgrade-cards/laminate-armor.png",
    "traits": [
      "Armor",
      "Medium"
    ],
    "type": "Armor"
  },
  {
    "id": 36,
    "tier": 2,
    "name": "Overcharger",
    "credits": 300,
    "image": "upgrade-cards/overcharger.png",
    "traits": [
      "Modification",
      "Energy"
    ],
    "type": "Ranged Weapon Modification"
  },
  {
    "id": 37,
    "tier": 2,
    "name": "Plasma Cell",
    "credits": 450,
    "image": "upgrade-cards/plasma-cell.png",
    "traits": [
      "Modification",
      "Energy"
    ],
    "type": "Ranged Weapon Modification"
  },
  {
    "id": 38,
    "tier": 2,
    "name": "R5 Astromech",
    "credits": 250,
    "image": "upgrade-cards/r5-astromech.png",
    "traits": [
      "Accessory"
    ],
    "type": "Equipment"
  },
  {
    "id": 39,
    "tier": 2,
    "name": "Slicing Tools",
    "credits": 250,
    "image": "upgrade-cards/slicing-tools.png",
    "traits": [
      "Accessory"
    ],
    "type": "Equipment"
  },
  {
    "id": 40,
    "tier": 2,
    "name": "Spread Barrel",
    "credits": 300,
    "image": "upgrade-cards/spread-barrel.png",
    "traits": [
      "Modification",
      "Barrel"
    ],
    "type": "Ranged Weapon Modification"
  },
  {
    "id": 41,
    "tier": 2,
    "name": "Stun Baton",
    "credits": 500,
    "image": "upgrade-cards/stun-baton.png",
    "traits": [
      "Staff"
    ],
    "type": "Melee Weapon"
  },
  {
    "id": 42,
    "tier": 2,
    "name": "T-21",
    "credits": 900,
    "image": "upgrade-cards/t-21.png",
    "traits": [
      "Blaster",
      "Heavy"
    ],
    "type": "Ranged Weapon"
  },
  {
    "id": 43,
    "tier": 2,
    "name": "Vibro Knucklers",
    "credits": 400,
    "image": "upgrade-cards/vibro-knucklers.png",
    "traits": [
      "Fist",
      "Blade"
    ],
    "type": "Melee Weapon"
  },
  {
    "id": 44,
    "tier": 2,
    "name": "Weighted Head",
    "credits": 400,
    "image": "upgrade-cards/weighted-head.png",
    "traits": [
      "Modification",
      "Balance"
    ],
    "type": "Melee Weapon Modification"
  },
  {
    "id": 45,
    "tier": 3,
    "name": "Admiral's Uniform",
    "credits": 350,
    "image": "upgrade-cards/admirals-uniform.png",
    "traits": [
      "Armor"
    ],
    "type": "Armor"
  },
  {
    "id": 46,
    "tier": 3,
    "name": "Ancient Lightsaber",
    "credits": 1000,
